### ISSUE TITLE
o.str.substr is not a function

### ISSUE THREAD

**Issue by Twisterking** [commenthol/date-holidays-parser#18]
Error:

```sh
Exception while invoking method 'getHolidays' TypeError: o.str.substr is not a function
     at Parser._shorten (/app/node_modules/date-holidays-parser/lib/Parser.js:192:21)
```
 

with the country 'AT':

```js
const Holidays = require('date-holidays');
let holidays = new Holidays();
holidays.init('AT');
holidays.getHolidays(2020); // ERROR
```

After some debugging:
```js
    key: "_shorten",
    value: function _shorten(o, cap0) {
      console.log({ o, cap0 });
      o.str = o.str.substr(cap0.length, o.str.length);
    }
```
it seems like that `o` and `cap0` are both `function`s!!

Please fix, this is very annoying as this completely breaks the whole library for me 😢

**Comment by leonidasv** [comment]
After some digging (tks @berreis), I've discovered that the problem lies in [`PostRule.js:89`](https://github.com/commenthol/date-holidays-parser/blob/04b586398519b9ae377f648cdb9e34f02daf0576/src/PostRule.js#L89):
```js
      for (const i in arr) {
        const p = parser.parse(arr[i]);
        ...
```

`for ... in` in Arrays is susceptible to Prototype overrides. So, if somewhere in your code you have something like:
```js
Array.prototype.something = function() { ...
```
The loop above will run into: 
```js
      for (const i = 'something' in arr) {
        const p = parser.parse(arr['something']);
```

And, since `arr['something']` is a `function`, the code will proceed and that function will get into `o.str` and `o.rule`. And, since functions have no `substr`, `_shorten()` will break.

This can also happen if your prototype override is a number, a boolean or anything else that's not a string.

I will submit a PR changing the `for in` approach to a `for of`, [which is the recommend approach for Arrays](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Statements/for...in) in JS.
